#!/usr/bin/env bash
# Universal Design Suite CLI Launcher for magic
if [ -x "/home/ubuntu/snap/antigravity-cli/common/nodejs/bin/magic" ]; then
    exec "/home/ubuntu/snap/antigravity-cli/common/nodejs/bin/magic" ""
elif [ -x "/home/ubuntu/snap/antigravity-cli/common/local/lib/node_modules/@21st-dev/magic/dist/index.js" ]; then
    exec "/home/ubuntu/snap/antigravity-cli/common/local/lib/node_modules/@21st-dev/magic/dist/index.js" ""
else
    exec npx -y @21st-dev/magic ""
fi
